[package]
name = "dump-pic"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[dependencies]
failure = ">= 0.1.2"
structopt = ">= 0.2"
ansi = { path = "../../libs/ansi" }
omnilib = { path = "../../libs/omnilib" }
pal = { path = "../../libs/pal" }
pic = { path = "../../libs/pic" }