image: archlinux
sources:
  - https://git.sr.ht/~terrence/openfa
packages:
  - cmake
tasks:
  - setup: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      source $HOME/.cargo/env
      rustup component add clippy-preview
      rustup component add rustfmt --toolchain stable-x86_64-unknown-linux-gnu
  - check-format: |
      cd openfa
      source $HOME/.cargo/env
      cargo fmt --all -- --check
  - check-clippy: |
      cd openfa
      source $HOME/.cargo/env
      cargo clippy --all -- --deny warnings --allow clippy::ref_in_deref
