[package]
name = "openfa"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]

[dependencies]
pal = { path = "libs/pal/" }
pic = { path = "libs/pic/" }
sh = { path = "libs/sh/" }
ot = { path = "libs/ot/" }
entity = { path = "libs/entity/" }
