[package]
name = "openfa"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[workspace]
members = [
        "apps/dump-pal",
        "apps/dump-pe",
        "apps/dump-pic",
        "apps/dump-sh",
        "apps/dump-asm",
        "apps/dump-lib",
        "apps/dump-vulkan",
        "apps/pack-pic",
        "apps/show-mm",
        "apps/show-dlg",
        "apps/show-sh",
        "apps/show-sh-raw",
        "apps/show-sky",

        "libs/animate",
        "libs/ansi",
        "libs/asset",
        "libs/dlg",
        "libs/fnt",
        "libs/i386",
        "libs/input",
        "libs/jt",
        "libs/lay",
        "libs/lib",
        "libs/lzss",
        "libs/mm",
        "libs/nt",
        "libs/omnilib",
        "libs/ot",
        "libs/packed_struct",
        "libs/pal",
        "libs/peff",
        "libs/pic",
        "libs/pkware",
        "libs/pt",
        "libs/legacy_render",
        "libs/renderer/atmosphere",
        "libs/renderer/base",
        "libs/renderer/camera",
        "libs/renderer/geometry",
        "libs/renderer/shape",
        "libs/renderer/stars",
        "libs/renderer/subocean",
        "libs/renderer/text",
        "libs/resource",
        "libs/reverse",
        "libs/sh",
        "libs/star_catalog",
        "libs/t2",
        "libs/window",
        "libs/xt",
]

# Emit debugging symbols for tracing
[profile.release]
debug = true

# Need profile-overrides from nightly
#[profile.dev.overrides.image]
#opt-level = 3

# pkware is unusable at opt level 0.
# [profile.dev.]
# opt-level = 2

# [profile.test]
# opt-level = 2

# [profile.test]
# opt-level = 1

[dependencies]