[package]
name = "openfa"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[dependencies]
failure = ">= 0.1.2"
humansize = ">= 1.0.1"
image = ">= 0.21"
log = ">= 0.4"
nalgebra = "^ 0.16"
num = ">= 0.2"
rand = ">= 0.6"
simplelog = ">= 0.5"
structopt = ">= 0.2"
vulkano = "^ 0.11.1"
vulkano-shaders = "^ 0.11.1"
vulkano-win = "^ 0.11.1"
winit = "^ 0.18"
ansi = { path = "libs/ansi/" }
asset = { path = "libs/asset/" }
dlg = { path = "libs/dlg" }
i386 = { path = "libs/i386/" }
jt = { path = "libs/jt/" }
lay = { path = "libs/lay/" }
lib = { path = "libs/lib/" }
lzss = { path = "libs/lzss/" }
mm = { path = "libs/mm/" }
nt = { path = "libs/nt/" }
omnilib = { path = "libs/omnilib/" }
ot = { path = "libs/ot/" }
packed_struct = { path = "libs/packed_struct/" }
pal = { path = "libs/pal/" }
peff = { path = "libs/peff/" }
pic = { path = "libs/pic/" }
pkware = { path = "libs/pkware/" }
pt = { path = "libs/pt/" }
render = { path = "libs/render/" }
resource = { path = "libs/resource/" }
reverse = { path = "libs/reverse/" }
sh = { path = "libs/sh/" }
t2 = { path = "libs/t2/" }
window = { path = "libs/window/" }
xt = { path = "libs/xt/" }