[package]
name = "dump-xt"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[dependencies]
failure = "^ 0.1.2"
simplelog = "^ 0.5"
structopt = "^ 0.2"
omnilib = { path = "../../libs/omnilib" }
xt = { path = "../../libs/xt" }
