[package]
name = "show-mm"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[dependencies]
failure = "^ 0.1.2"
image = "^ 0.21"
log = "^ 0.4"
nalgebra = "^ 0.18"
simplelog = "^ 0.5"
structopt = "^ 0.2"
vulkano = "^ 0.14"
vulkano-shaders = "^ 0.14"
vulkano-win = "^ 0.14"
winit = "^ 0.19"
asset = { path = "../../libs/asset" }
camera = { path = "../../libs/render-shared/common/camera" }
input = { path = "../../libs/render-vulkano/common/input" }
lay = { path = "../../libs/lay" }
lib = { path = "../../libs/lib" }
mm = { path = "../../libs/mm" }
omnilib = { path = "../../libs/omnilib" }
pic = { path = "../../libs/pic" }
pal = { path = "../../libs/pal" }
legacy_render = { path = "../../libs/legacy_render" }
t2 = { path = "../../libs/t2" }
text = { path = "../../libs/render-vulkano/draw/text" }
xt = { path = "../../libs/xt" }
window = { path = "../../libs/render-vulkano/common/window" }
