[package]
name = "shape_explorer"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]

[dependencies]
clap = "2.29"
glfw = "0.15"
kiss3d = "0.11"
nalgebra = "0.13"
pal = { path = "../../libs/pal/" }
pic = { path = "../../libs/pic/" }
sh = { path = "../../libs/sh/" }
