[package]
name = "shape_explorer"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]

[dependencies]
shape = { path = "../../libs/shape/" }
kiss3d = "0.11"
nalgebra = "0.13"
clap = "2.29"
