[package]
name = "nitrogen"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "apps/dump-terrain-tables",

    "libs/sim/absolute_unit",
    "libs/sim/geodesy",
    "libs/sim/physical_constants",
]

[dependencies]
