[package]
name = "disasm"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[dependencies]
failure = ">= 0.1.2"
simplelog = ">= 0.5.0"
structopt = ">= 0.2"
i386 = { path = "../../libs/i386" }