[package]
name = "show-sky"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[dependencies]
failure = "^ 0.1.2"
image = "^ 0.21"
log = "^ 0.4"
nalgebra = "^ 0.18"
simplelog = "^ 0.5"
structopt = "^ 0.2"
vulkano = "^ 0.14"
vulkano-shaders = "^ 0.14"
vulkano-win = "^ 0.14"
winit = "^ 0.19"
camera = { path = "../../libs/render/common/camera" }
input = { path = "../../libs/input" }
lib = { path = "../../libs/lib" }
pal = { path = "../../libs/pal" }
skybox = { path = "../../libs/render/draw/skybox" }
text = { path = "../../libs/render/draw/text" }
window = { path = "../../libs/window" }
