[package]
name = "show-sky"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[dependencies]
failure = "^ 0.1.2"
image = "^ 0.21"
log = "^ 0.4"
nalgebra = "^ 0.18"
simplelog = "^ 0.5"
structopt = "^ 0.2"
#wgpu = { git="https://github.com/gfx-rs/wgpu-rs.git", rev="697393df4793e1a58578209885036114adfb9213" }
wgpu = { git="https://github.com/terrence2/wgpu-rs.git", branch="tdc/wgpu-work-head" }
#wgpu = { path="/home/terrence/Projects/wgpu-rs" }
atmosphere = { package = "atmosphere-wgpu", path = "../../libs/render-wgpu/buffer/atmosphere" }
camera = { path = "../../libs/render-shared/common/camera" }
frame_graph = { package = "frame_graph-wgpu", path = "../../libs/render-wgpu/common/frame_graph" }
fullscreen = { package = "fullscreen-wgpu", path = "../../libs/render-wgpu/buffer/fullscreen" }
global_data = { package = "global_data-wgpu", path = "../../libs/render-wgpu/buffer/global_data" }
gpu = { path = "../../libs/render-wgpu/common/gpu" }
input = { package = "input-wgpu", path = "../../libs/render-wgpu/common/input" }
lib = { path = "../../libs/lib" }
pal = { path = "../../libs/pal" }
screen_text = { package = "screen_text-wgpu", path = "../../libs/render-wgpu/render_pass/screen_text" }
skybox = { package = "skybox-wgpu", path = "../../libs/render-wgpu/render_pass/skybox" }
stars = { package = "stars-wgpu", path = "../../libs/render-wgpu/buffer/stars" }
text_layout = { package = "text_layout-wgpu", path = "../../libs/render-wgpu/buffer/text_layout" }
