[package]
name = "dump-lay"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[dependencies]
failure = "^ 0.1.2"
omnilib = { path = "../../libs/omnilib" }
lay = { path = "../../libs/lay" }
pal = { path = "../../libs/pal" }
