[package]
name = "show-sh"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[dependencies]
failure = "^ 0.1.2"
image = "^ 0.21"
legion = "= 0.2.4"
log = "^ 0.4"
nalgebra = "^ 0.20"
simplelog = "^ 0.5"
structopt = "^ 0.2"
absolute_unit = { path = "../../libs/nitrogen/sim/absolute_unit" }
atmosphere = { path = "../../libs/render-wgpu/buffer/atmosphere" }
camera = { path = "../../libs/nitrogen/sim/camera" }
command = { path = "../../libs/nitrogen/system/command" }
fnt = { path = "../../libs/fnt" }
frame_graph = { path = "../../libs/nitrogen/system/frame_graph" }
fullscreen = { path = "../../libs/render-wgpu/buffer/fullscreen" }
geodesy = { path = "../../libs/nitrogen/sim/geodesy" }
font_fnt = { path = "../../libs/render-wgpu/buffer/font_fnt" }
galaxy = { path = "../../libs/galaxy" }
global_data = { path = "../../libs/render-wgpu/buffer/global_data" }
gpu = { path = "../../libs/nitrogen/system/gpu" }
input = { path = "../../libs/nitrogen/system/input" }
lib = { path = "../../libs/lib" }
omnilib = { path = "../../libs/omnilib" }
orrery = { path = "../../libs/nitrogen/sim/orrery" }
screen_text = { path = "../../libs/render-wgpu/render_pass/screen_text" }
shape = { path = "../../libs/render-wgpu/render_pass/shape" }
shape_instance = { path = "../../libs/render-wgpu/buffer/shape_instance" }
skybox = { path = "../../libs/render-wgpu/render_pass/skybox" }
stars = { path = "../../libs/render-wgpu/buffer/stars" }
text_layout = { path = "../../libs/render-wgpu/buffer/text_layout" }
