[package]
name = "dump-vulkan"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[dependencies]
failure = ">= 0.1.2"
vulkano = "^ 0.12"
vulkano-win = "^ 0.12"
winit = "^ 0.19"
